### ISSUE TITLE
Upgrade http to https

### ISSUE THREAD

**Issue by BroJac5246** [newshopchannel/wiiweb#1]
Self-explanatory 

I think it's free but I forget how you do it

**Comment by trlandrew** [comment]
wdym register for https?

**Comment by BroJac5246** [comment]
If you go to wii.ftolnks.xyz then you get a warning about how it's using `http` and not `https`. I've never done it before, but my understanding is that you need to go to a Certificate Authority and get a certificate.

**Comment by trlandrew** [comment]
Oh. It's supposed to be HTTP because Internet Channel loads websites when they don't have a SSL certificate. No idea why.

**Comment by trlandrew** [comment]
Also, you don't need to go to a certificate authority or someone else, we made our SSL certificates via Let's Encrypt, and it was free.

**Comment by BroJac5246** [comment]
> Also, you don't need to go to a certificate authority or someone else, we made our SSL certificates via Let's Encrypt, and it was free.

My understanding is that Let's Encrypt is a certificate authority; it says so on their website.

**Comment by BroJac5246** [comment]
> Oh. It's supposed to be HTTP because Internet Channel loads websites when they don't have a SSL certificate. No idea why.

Will most people visit this from the Internet Channel? (They're the ones I based the claim that it's free on)

**Comment by BroJac5246** [comment]
> Oh. It's supposed to be HTTP because Internet Channel loads websites when they don't have a SSL certificate. No idea why.

Will most people visit this from the Internet Channel? If you visit it from a modern web browser, you get a big warning about the site not being secure, which could turn people away.
